theme: minima
title: Programming - A beginner's journal
author: Sophiehwl2177
email: Sophiehwl2177@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This is a journal for a beginner, in trying to self-learning programming

# social links
twitter_username: sophiehwl2177 # DO NOT include the @ character, or else the build will fail!
github_username:  Sophiehwl2177 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
